services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: erik2962917
      PGDATA: /data/foodroulett
    volumes:
      - db:/data/foodroullett
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
    
volumes:
  db: